last

diff --git a/.github/workflows/block-fixup-commits.yaml b/.github/workflows/block-fixup-commits.yaml
--- a/.github/workflows/block-fixup-commits.yaml
+++ b/.github/workflows/block-fixup-commits.yaml
@@ -6,7 +6,6 @@ on:
 env:
   RED: '\033[0;31m'
   YELLOW: '\033[0;33m'
-  NO_COLOUR: '\033[0m'
 
 
 jobs:
@@ -16,15 +15,9 @@ jobs:
     steps:
     - name: Checkout our main branch
       uses:  actions/checkout@v3
-    
-    - name: Echo remotes
-      run: git remote -v 
 
     - name: Add fork as remote
       run: git remote add fork ${{ github.event.pull_request.head.repo.clone_url  }}
-
-    - name: Echo remotes
-      run: git remote -v
 
     - name: Fetch the pull request's branch
       run: git fetch fork ${{ github.event.pull_request.head.ref }} --depth=$((${{ github.event.pull_request.commits }} + 1 ))
@@ -33,12 +26,12 @@ jobs:
       id: search-for-fixup-prefix
       run: |
         commit_messages=$(git log origin/${{ github.event.pull_request.base.ref }}..fork/${{ github.event.pull_request.head.ref }} --format="%h %B" --grep "^fixup" --oneline)
-        if [ -n "$commit_messages" ]; then
-            echo -e "$RED Error: Please make sure that all commits that have the 'fixup' prefix need to be squashed before merging."
+        if [ -n "commit_messages" ]; then
+            echo -e "$RED Error: Make sure that all 'fixup' prefixed commits are squashed before merging."
             echo -e "$RED Commits that need fixing:"
             while IFS= read -r line; do
               echo -e "$YELLOW${line}"
             done <<< "$commit_messages"
             exit 1
+            exit 1
         fi
-    
